document.addEventListener("DOMContentLoaded", function() {
    const searchInput = document.getElementById("searchInput");
    const lexicon = document.getElementById("lexicon");
    const alphabetMenu = document.getElementById("alphabetMenu");

    // Liste des termes et de leurs définitions
    const glossary = [
        { term: "HTML", definition: "HyperText Markup Language. Le langage de balisage standard pour la création de pages Web." },
        { term: "CSS", definition: "Cascading Style Sheets. Le langage utilisé pour définir le style et la présentation des pages Web." },
        { term: "JavaScript", definition: "Un langage de programmation utilisé pour rendre les pages Web interactives et dynamiques." },
        { term: "Framework", definition: "Une structure logicielle qui fournit des outils et des bibliothèques pour simplifier le processus de développement d'applications. Les frameworks web populaires incluent React.js, Angular et Vue.js."},
        {term:"API", definition:"Application Programming Interface. Un ensemble de règles et de protocoles qui permettent à différentes applications logicielles de communiquer entre elles. Les API sont utilisées pour accéder à des fonctionnalités ou à des données à partir d'autres applications ou services."},
        {term:"DOM", definition:"Document Object Model. Une représentation hiérarchique en arbre de la structure d'un document HTML. Le DOM permet aux programmes JavaScript d'accéder et de manipuler les éléments HTML, de modifier le contenu de la page et de réagir aux événements utilisateur."},
        {term:"MVC", definition:"Model-View-Controller. Un modèle de conception logicielle qui divise une application en trois composants principaux : le modèle (qui représente les données), la vue (qui affiche l'interface utilisateur) et le contrôleur (qui gère les interactions utilisateur et met à jour le modèle et la vue en conséquence)."},
        {term:"REST", definition:"Representational State Transfer. Un style d'architecture logicielle utilisé pour concevoir des services web et des API qui sont simples, évolutifs et interopérables. Les services REST utilisent des opérations HTTP standard (GET, POST, PUT, DELETE) pour accéder et manipuler des ressources."},
        {term:"Git", definition:"Un système de contrôle de version distribué largement utilisé pour le suivi des modifications apportées au code source d'un projet logiciel. Git permet aux développeurs de collaborer efficacement sur des projets, de gérer les branches de développement et de revenir en arrière sur les modifications si nécessaire."},
        {term:"npm", definition:"Node Package Manager. Un gestionnaire de paquets pour le langage de programmation JavaScript. npm est utilisé pour installer, gérer et partager des packages JavaScript et des dépendances pour les projets Node.js."},
        {term:"HTTPS", definition:"Hypertext Transfer Protocol Secure. Une extension sécurisée du protocole HTTP utilisé pour transférer des données sur Internet. HTTPS utilise un cryptage SSL/TLS pour sécuriser les communications entre le navigateur de l'utilisateur et le serveur web."},
        {term:"XSS", definition:"Cross-Site Scripting. Une faille de sécurité qui permet à un attaquant d'injecter du code JavaScript malveillant dans une application web, généralement via des champs de formulaire ou des URL, et de l'exécuter dans le navigateur d'un utilisateur."},
        {term:"CSRF", definition:"Cross-Site Request Forgery. Une attaque de sécurité où un attaquant force un utilisateur authentifié à exécuter des actions non autorisées sur un site web auquel l'utilisateur est déjà connecté."},
        {term:"AJAX", definition:"Asynchronous JavaScript and XML, est une technologie utilisée dans le développement web pour créer des applications interactives en permettant aux pages web de communiquer avec le serveur en arrière-plan sans recharger toute la page. Plutôt que de rafraîchir toute la page à chaque interaction de l'utilisateur, AJAX permet de mettre à jour dynamiquement certaines parties de la page avec de nouvelles données, souvent en utilisant des requêtes HTTP asynchrones. Cela permet une expérience utilisateur plus fluide et réactive, car les actions de l'utilisateur peuvent être traitées de manière asynchrone, sans bloquer ou interrompre la navigation. AJAX est largement utilisé pour la création d'applications web modernes ( applications de messagerie instantanée, systèmes de cartographie interactifs, applications de médias sociaux...)."},
        {term:"Algorithme", definition:"Un ensemble d’instructions détaillées et précises qui décrivent une série de étapes à suivre pour résoudre un problème ou accomplir une tâche. Les algorithmes peuvent être utilisés pour effectuer des calculs, traiter des données, prendre des décisions et accomplir d’autres tâches informatiques."},
        {term:"AMP", definition:"Accelerated Mobile Page, ou AMP, est une technologie open-source, permettant d’améliorer le temps de chargement de votre site web et de l’optimiser pour le SEO, en proposant une version simplifiée du langage HTML du site internet en question. Les éléments JavaScript sont contournés afin d’éviter toutes détériorations des performances. Cette technique permet d’améliorer l’expérience utilisateur."},
        {term:"APACHE HTTP SERVEUR", definition:"Apache HTTP Server (souvent appelé simplement Apache) est un serveur Web libre et open source pour les systèmes d’exploitation Unix-like, Windows et MacOS. Il est l’un des serveurs Web les plus populaires au monde. Il est connu pour sa flexibilité, sa stabilité et sa performance. Apache peut être configuré de différentes manières pour répondre aux besoins spécifiques d’un site Web, il peut également être utilisé en conjonction avec d’autres logiciels pour créer et gérer des sites Web dynamiques."},
        {term:"BACK-END", definition:"Le back-end d’un site ou d’une application Web fait référence à la partie qui est « cachée » aux utilisateurs et qui se trouve sur le serveur. C’est la partie du site ou de l’application qui s’occupe de la logique de l’application, de la gestion de la base de données et de la communication avec les utilisateurs."},
        {term:"BACK-OFFICE", definition:"Le back-office est la partie invisible d’un site web. Elle est protégée par un mot de passe permettant de gérer l’ensemble du site. Cette interface permet d’administrer votre site internet. Chez Digital Cover, nos clients ont la possibilité d’effectuer des modifications comme l’intégration de nouveaux contenus ou d’articles par exemple. "},
        {term:"BASE DE DONNÉES", definition:"Une base de données est un système organisé qui stock des informations et permet de les récupérer, de les mettre à jour et de les manipuler de différentes manières. Les bases de données sont couramment utilisées pour stocker et gérer de grandes quantités de données de manière organisée et accessible, de manière à ce qu’elles puissent être utilisées efficacement."},
        {term:"BIG DATA", definition:"Les Big Data, également appelées mégadonnées, désignent de grandes quantités de données structurées et non structurées qui sont difficiles à traiter et à analyser à l’aide de technologies et de techniques traditionnelles. Elles peuvent provenir de différentes sources, telles que les transactions en ligne, les réseaux sociaux, les capteurs et les appareils connectés, et peuvent être utilisées pour obtenir des insights et des prévisions sur les comportements et les tendances."},
        {term:"CDN", definition:"Content Delivery Network (réseau de diffusion de contenu), il s’agit d’un ensemble de serveurs localisé à des emplacements différents et mis en réseau par internet. C’est un moyen très pertinent de diffuser votre site ou application web dans le monde. A travers un système de répartition, les contenus statiques de votre serveur sont envoyés vers des serveurs miroirs. Lorsqu’un internaute charge un contenu spécifique sur votre site, la demande est envoyée par un système d’acheminement des demandes vers le serveur miroir le mieux adapté du CDN afin de délivrer les données correspondantes. "},
        {term:"CGI", definition:"Common Gateway Interface (CGI) est une spécification qui définit comment un serveur Web peut interagir avec des programmes exécutables sur le serveur. Il permet aux utilisateurs de créer des pages Web dynamiques en exécutant des scripts ou des programmes sur le serveur lorsqu’une page est demandée par un utilisateur. Le CGI est généralement utilisé avec des langages de script côté serveur tels que PHP, Perl ou Python. Lorsqu’un utilisateur demande une page Web qui utilise le CGI, le serveur exécute le script ou le programme associé et renvoie le résultat sous forme de page Web générée dynamiquement au navigateur de l’utilisateur. "},
        {term:"CLIENT SIDE", definition:"Le client side se définit par toutes les interactions physiques possibles lors de la navigation sur un site web. Le langage HTML et CSS sont interprétés du côté client via des interprétations des données reçues par le serveur. Par exemple, lorsqu’un utilisateur navigue sur votre site sa souris peut survoler une image et celle-ci devient plus grande, le texte peut changer de couleur… "},
        {term:"CMS", definition:"Content Management System, un CMS regroupe une catégorie de logiciels permettant de gérer et mettre à jour les sites internet. Plus spécifiquement, les CMS servent à scinder le contenu de la mise en forme."},
        {term:"SCSS (SASS)", definition:"SCSS (SASS) est un pré-processeur représentant une sur-couche de CSS qui va permettre d’automatiser, organiser les fichiers plus facilement, simplifier l’utilisation du code ou encore diminuer les erreurs. De plus, cela améliore la qualité et le temps de développement."},
        {term:"FRONT-OFFICE", definition:"Au contraire du back-office, le front-office est la partie visible de votre site web par les utilisateurs. Il s’agit de l’ensemble des pages web qui ont été réalisées par le développeur, elles représentent la partie exposée d’un site web. Les utilisateurs peuvent naviguer et visualiser cette partie sans restriction. "},
        {term:"FTP", definition:" File Transfer Protocol, le FTP est un logiciel utilisé pour le transfert de fichiers entre différents ordinateurs. Ce logiciel, par le biais d’un réseau informatique local tel qu’un intranet ou par un navigateur internet, permet une facilité dans les échanges de fichiers. "},
        {term:"FULL-STACK", definition:"Un développeur full-stack est capable de réaliser la programmation d’un site internet ou d’une application web en front-end et en back-end. Le full-stack est utilisé lorsqu’un développeur travaille sur le front et le back end."},
        {term:"HEADLESS CMS", definition:"Système de gestion de contenu, le headless se compose d’une API et de la technologie du back-office pour stocker et distribuer le contenu. Cette approche permet de découpler l’édition et la distribution du contenu, afin d’offrir la possibilité d’utiliser les données du CMS quelque soit la plateforme. De plus, cette technologie permet d’administrer les différents types d’affichages des contenus sur une ou plusieurs plateformes. "},
        {term:"IDE", definition:"Integrated Development Environment (environnement de développement intégré) est un logiciel de création d’applications regroupant les outils de développements les plus utilisés dans une seule interface. Les développeurs ont accès à tous types de fichiers avec différentes arborescences, couleurs, lignes de codes… Chez Digital Cover nos experts travaillent sous le logiciel Visual Studio Code. "},
        {term:"LAZY LOADING", definition:"Le lazy loading est le fait de charger les images et vidéos en différé, c’est-à-dire uniquement lorsqu’elles deviennent visibles sur l’écran en fonction du scroll. Cette pratique permet de faire gagner en performance, de réduire le temps de chargement du site ou encore d’améliorer le référencement naturel. "},
        {term:"MAMP", definition:"(acronyme informatique : Macintosh pour le système d’exploitation ; Apache pour le logiciel de serveur web ; MySQL pour le système de gestion des bases de données ; PHP pour le langage script) C’est en réalité une pile de logiciels open source utilisés pour réaliser des sites internet via des ordinateurs Mac en créant un serveur local sur son ordinateur."},
        {term:"MEDIA QUERIES", definition:"désigne un module permettant d’adapter le contenu d’une page web à des conditions spécifiques. Ce module est mis à contribution lors de la modification de l’affichage d’une page selon sa hauteur et largeur en fonction de l’écran utilisé pour sa navigation. Le media queries est une spécification CSS3 dans la création d’un site responsive. L’intégration du media queries dans le développement d’un site internet offre un gain de temps par rapport à la conception d’une interface différente pour chacun des supports. "},
        {term:"MOBILE FIRST", definition:"stratégie digitale qui consiste à concevoir et développer son site web pour tous types de mobiles et en adaptant au fur et à mesure le design pour des écrans plus larges. "},
        {term:"PARALLAX", definition:"La technique du parallax, ou parallax scrolling en anglais, permet de déplacer une image ou un visuel positionné sous différentes « couches ». L’image/visuel donne l’impression de changer de position au scroll de la page web. Nos développeurs web vont attribuer une vitesse plus rapide à l’objet à contrario de celle du fond. Ce changement de vitesse donne un effet de profondeur sur le ou les visuels et une mise en avant de vos contenus."},
        {term:"PHP", definition:" Personal Home Page, ce langage de scripts et open source est conçu pour le développement d’applications web. Il offre la possibilité d’écrire en HTML dans un fichier PHP permettant d’avoir des variables modifiables et d’être répété dans le code du fichier PHP. "},
        {term:"PLUGIN", definition:"Le plugin permet d’ajouter des fonctions supplémentaires à un logiciel. C’est un module d’extension ne pouvant fonctionner seul. En effet, il est dépendant de son logiciel hôte. Les plugins sont souvent utilisés pour ajouter des fonctionnalités. Par exemple, sous WordPress le plugin Yoast vous permet d’avoir des recommandations SEO concernant votre page. Il existe un grand nombre de plugins pour vous aider. "},
        {term:"PWA", definition:"La Progressive Web App, ou PWA, est une technologie employée permettant à votre site web de s’afficher comme une application mobile native à vos utilisateurs. La PWA possède quelques avantages comme la possibilité d’y avoir accès même hors connexion. L’interface et la navigation sera semblable à une application mobile, notifications push disponible, GPS, appareil photo, ainsi que la possibilité de l’installer sur votre téléphone."},
        {term:"RECETTE", definition:"vérification de la conformité fonctionnelle et technique d’un produit en cours ou à la fin de sa conception et de son développement."},
        {term:"RESPONSIVE", definition:"Un site responsive design est un site web qui à la capacité d’adapter son affichage à tous les types d’écran (mobile, tablette, PC sont les plus courants)."},
        {term:"SERVER SIDE", definition:"Le côté serveur en français, désigne tout ce qui se déroule sur le serveur et non sur le côté client. C’est en réalité les opérations effectuées par le serveur dans la communication entre le client et le serveur dans le réseau informatique. "},
        {term:"SHADER", definition:"Un shader est un programme qui communique directement avec la carte graphique. Il permet de réaliser des animations et des effets graphiques poussés, mais aussi de réaliser des rendus 3D dans un navigateur. "},
        {term:"STARTER", definition:"Le starter est un ensemble de fichiers et de fonctionnalités mis à jour constamment lors de chaque création de site internet. Il fait l’objet de notre base de démarrage pour chaque lancement de projet."},
        {term:"WEBP / AVIF", definition:"WEBP et AVIF sont des formats de média optimisés pour le web. Ils permettent de gagner en performance par rapport à différents formats d’image tels que JPEG, PNG.. "},
        {term:"WebGL", definition:"Cette spécification, pour les navigateurs web (Google Chrome, Firefox, Edge, Safari) permet de mettre en place des animations poussées en 2D ou 3D sur les pages web d’un site internet. Il permet de limiter les performances en utilisant principalement la carte graphique, ce qui rendra le site plus fluide dans sa navigation."},
        {term:"Tests unitaires", definition:"tests réalisés par du code (souvent avec des Frameworks dédiés)."},
        {term:"Tests", definition:"contrôles effectués au cours des différentes phases d’un projet (ou cycle de vie) afin de vérifier l’adéquation entre ce qui est livré et ce qui était attendu pour chaque phase. Exemples : test d’intégration, test de non-régression, test de performance, test de réception, test unitaire, test de validation."},
        {term:"Système d’exploitation ", definition:"(SE ou OS en anglais) ensemble des programmes informatiques qui pilote les différents composants de l’appareil informatique (disque dur, écran, processeur, mémoire etc…) et qui lui permet donc de fonctionner. Il gère également la mémoire, les supports de stockage et les droits d’accès des utilisateurs."},
        {term:"Scrum", definition:"Méthode de développement agile, animée par un ScrumMaster"},
        {term:"Serveur", definition:"ordinateur dont les données (fichiers) sont partagées en interne, via l’intranet (réseau interne d’une entreprise) ou l’extranet. Le serveur est relié au monde extérieur par internet. De nombreuses entreprises utilisent également des serveurs pour héberger et « servir » leurs sites Internet et leurs données d’applications (via une API, par exemple)."},
        {term:"Repository", definition:" (ou « Repo ») Entrepôt de code, gestionnaire de code source."},
        {term:"Refonte", definition:"modifier totalement ou en partie un site internet ou une application."},
        {term:"Proxy", definition:"un ordinateur ou un module qui sert d’intermédiaire entre un navigateur Web et Internet. Le proxy participe à la sécurité et à la performance du réseau en sécurisant et améliorant l’accès à certaines pages Web."}, 
        {term:"Programmer", definition:"réaliser un programme informatique. La phase de programmation n’inclut généralement que les actions de codage, et non celles de conception ou de test . Mais il est possible de programmer également des tests automatisés (réalisés en code)."},
        {term:"Programme", definition:"ensemble d’instructions effectuant des actions sur un ordinateur. L’organisation des instructions est conçue et rédigée par un programmeur dans un langage de programmation."},
        {term:"Plug-in", definition:"extension qui ajoute des fonctionnalités aux logiciels. Ces programmes complémentaires permettent par exemple aux navigateurs de lire certains formats d’image, de vidéo, d’animation ou de son, etc."},
        {term:"Product Owner", definition:"rôle au sein de l’organisation d’une équipe Agile utilisant la méthodologie SCRUM. Le PO a pour mission principale de définir et conceptualiser un produit qui saura apporter le maximum de valeur aux utilisateurs, dans le temps et le budget impartis au projet."},
        {term:"Mise en production", definition:"mise en place d’une application informatique dans son contexte réel d’utilisation (environnement technique et logiciel) ainsi que de tous les éléments requis pour son exploitation et sa pérennité."},
        {term:"Méthodes agiles", definition:"méthodes de gestion et de développement, particulièrement adaptées aux projets ou programmes informatiques, et qui fonctionnent sur la base de l’itératif (partir d’une idée grossière que les équipes affinent par retouches successives, chacune améliorant la qualité et peaufinant l’idée de départ) et l’incrémental (idée initiale complètement formée, que l’on construit ensuite morceau par morceau, jusqu’à la livraison du produit fini). Les méthodes agiles se déclinent en de nombreuses versions ou applications, dont deux des plus répandues sont la méthode Scrum et la méthode Kanban."}, 
        {term:"Lead dev", definition:"développeur référent, qui peut être référent sur une technologie en particulier ou sur un produit. Il n’y a donc pas forcément de notion hiérarchique."},
        {term:"Backlog", definition:"Liste des « features » à traiter en méthode agile."},
        {term:"Backup", definition:"Sauvegardes"},
        {term:"Balises", definition:"partie de code de programmation destinée à la création et à la structure d’une page internet, ou utilisée par les moteurs de recherche afin de mieux analyser un élément."},
        {term:"Blog", definition:"site Web caractérisé par la publication régulière de billets ou de « post », à l’image d’un journal de bord. Le blogueur (rédacteur qui tient le blog) y rédige un contenu souvent textuel, enrichi d’hyperliens et d’éléments multimédias, sous lequel chaque lecteur peut généralement apporter des commentaires."},
        {term:"CDC", definition:"Cahier des charges. Les professionnels évoluant en méthodes agiles y ont moins recours, mais le CDC reste encore aujourd’hui une pratique courante."}, 
        {term:"Codage", definition:"action réalisée par un programmeur qui écrit le code source d’un programme et le compile."},
        {term:"Code source", definition:"Version d’un programme que l’humain peut comprendre. En d’autres termes, les instructions du programme sont rédigées dans un langage de programmation créé et maîtrisé par l’homme. Inversement, le code exécutable est la version compilée du code source, qui prend la forme d’une suite de codes binaires compréhensible de l’ordinateur seulement."}, 
        {term:"Compiler", definition:"générer le code exécutable d’un programme à partir du code source."},
        {term:"Développer", definition:"réaliser une application ou un site web."}, 
        {term:"Feature", definition:"Fonctionnalité d’une application ou d’un site web en développement."},
        {term:"Intégration", definition:"consiste à réunir au sein d’un même système d’information, des parties développées de façon séparées. L’intégration peut également consister à la tâche effectuée par le développeur Front-End (aussi appelé intégrateur)."}, 
        {term:"Langages de programmation", definition:"langage permettant de formuler des algorithmes et de produire des programmes informatiques qui appliquent ces algorithmes. Parmi les langages les plus utilisés, citons par exemple Java, JavaScript, PHP, SQL, J2EE, HTML, .NET…"},
        {term:"BSon", definition:"BSon est le format Binaire de JSon. Il est notamment utilisé en NoSQL comme avec MongoDB."}, 
        {term:"Livraison Continue (CD)", definition:"Continuous Delivery, ou Livraison Continue, est un ensemble de pratiques qui suit souvent l’Intégration Continue. Elle vise à déployer de manière automatique et sur les bons supports, le code source validé lors de l’action d’Intégration Continue."},
        {term:"Intégration Continue (CI)", definition:"Continuous Integration, ou Intégration Continue, est un ensemble de pratiques permettant, de manière automatique, la vérification du code source. Cela se fait à travers des outils d’automatisation qui lorsqu’un développeur va push sur Git va déployer une suite d’opérations de compilation, tests unitaires, fonctionnels, validation du produit, etc.."}, 
        {term:"Commit", definition:"Dans le versionning, commit est l’action d’enregistrer et de préparer des fichiers pour les envoyer sur le serveur."},
        {term:"Compilé", definition:"Se dit d’un langage qui va être transformé – compilé – par un compilateur en un code binaire (non compréhensible par l’Homme). C’est directement l’OS qui va utiliser ce code de manière simple et rapide. (Exemple: les fichiers .exe sous Windows)"}, 
        {term:"Cloud computing", definition:"Le Cloud Computing représente la mise à disposition d’un parc de machines, de réseaux et/ou de logiciels à travers internet. Le fournisseur gère la maintenance et le client paye donc l’accès et l’utilisation dudit service."},
        {term:"Crossplateforme", definition:"Se dit d’une technologie ou d’un langage qui permet de développer une seule fois pour différents supports (mobile, ordinateur et web par exemple)"}, 
        {term:"DevOps", definition:"Le DevOps est un mouvement qui vise à unifier les unités de développement et d’opération. Historiquement, les dév et les ops (admin sys) n’avaient que très peu d’échanges. Aujourd’hui, les deux métiers sont étroitement liés grâce à toute l’automatisation mis en place."},
        {term:"DNS", definition:"DNS, ou Domain Name System, est le service qui permet la traduction d’un nom de domaine en adresse IP. En effet, chaque nom de domaine (www.google.fr) est associé à une adresse IP qui est finalement l’adresse du serveur."}, 
        {term:"Desktop As A Service (DaaS)", definition:"Desktop as a Service, est un modèle de cloud computing. Le but est de mettre à disposition un bureau virtuel à disposition à travers le cloud. C’est ce que fait la société Shadow en louant des ordinateurs gamers à travers le cloud."},
        {term:"From Scratch", definition:"On dit d’une application web qu’elle a été développée « from scratch » lorsque pour la coder, ni frameworks ni bibliothèques n’ont été utilisés. Le développement a donc été fait à partir de rien."}, 
        {term:"Frontend", definition:"Le front-end désigne toutes les techniques permettant de créer le front-office. On parle donc des différentes technologies, des logos, du choix des couleurs, de la mise en place des maquettes pour créer un joli visuel sur une application."},
        {term:"Backend", definition:"Le back-end, tout comme le front-end correspond à toutes les techniques permettant de gérer les données acquises par la partie front-office. On y retrouve les bases de données, les serveurs, le code permettant d’enregistrer les informations ou de les vérifier."}, 
        {term:"GitHub", definition:"Github est une des plateformes permettant d’accéder visuellement aux différentes versions de son code managé par le logiciel Git. Github est donc une interface graphique. (backoffice)"},
        {term:"GitLab", definition:"GitLab est une autre plateforme similaire à GitHub. Sa différence réside entre autre dans sa capacité à être déployé sur un serveur en interne contrairement à GitHub qui est forcément hébergé dans le cloud. Les pipelines sont aussi très utilisées pour du CI/CD."}, 
        {term:"Hybride", definition:"Se dit d’un développement utilisant un langage permettant d’être le même pour différentes plateformes. (Souvent du HTML/CSS/JS) Par exemple, ReactJS permet de créer des applications hybrides avec un seul code pour les différentes plateformes iOS et Android."},
        {term:"Hyperviseur", definition:"L’hyperviseur existe sous différents types. C’est le logiciel qui va permettre de créer et manager les différentes VM (machines virtuelles) Chez le particulier, on utilise un hyperviseur de type 2 comme VirtualBox par exemple."}, 
        {term:"Home Made (CMS Fait Maison)", definition:"On peut souvent entendre ce terme lorsqu’un outil non existant a été créé spécialement pour le besoin de l’entreprise ou d’une personne. L’outil est donc fait maison pour répondre spécifiquement aux attentes. C’est souvent le cas pour des CMS HomeMade à base de Zend ou Symfony."},
        {term:"Internet", definition:"Internet, c’est le réseau mondial accessible au public. C’est un réseau de réseaux, ce que nous connaissons le mieux."}, 
        {term:"Intranet", definition:"Intranet, c’est un réseau clos accessible de manière privé. C’est souvent un réseau d’entreprise. Mais il utilise les mêmes protocoles qu’Internet"},
        {term:"Infrastructure As A Service (IaaS)", definition:"Infrastructure as a Service, est un modèle de cloud computing. Le but est de mettre à disposition une infrastructure informatique (serveurs, stockage, sauvegarde, réseau) à disposition à travers le cloud. Exemple avec OVH qui loue des serveurs virtualisés ou privés."}, 
        {term:"JSon", definition:"JSon, JavaScript Object Notation, est un format de données issu et très adapté au monde JavaScript. Le JSon se base sur une association clé/valeur permettant le stockage facile de données."},
        {term:"Library", definition:"Une library, ou librairie ou encore bibliothèque, est un fichier ou un ensemble de fichiers qui visent à répondre à un besoin précis. Il faut donc voir ça comme un outil dans une boite à outils."},
        {term:"Local", definition:"Développer en local signifie développer sur sa propre machine de travail, son ordinateur."}, 
        {term:"Logs", definition:"Les logs sont des messages permettant de tracer des informations importantes dans l’exécution de notre code. On peut avoir différents types de logs commes des infos ou des erreurs."},
        {term:"Merise", definition:"Merise est une méthode d’analyse et de conception liée aux BDDs. Merise possède une approche très complexe mais très puissante pour des projets à architecture lourde et complexe."}, 
        {term:"Natif", definition:"Se dit d’un développement utilisant le langage d’origine du périphérique cible. Par exemple, le développement natif mobile sera Java pour Android et Objective-C/Swift pour iOS."},
        {term:"Nom de domaine (NDD)", definition:"DN, ou Domain Name ou encore Nom De Domaine, est un identifiant au format nom-de-domaine.extension qui permet de facilement accéder à la ressource à laquelle il est attaché. La plupart du temps, un DN est utilisé pour un site internet, donc rattaché à l’adresse IP du serveur qui héberge le site."},
        {term:"Persona", definition:"Le persona est une personne fictive dotée des attributs et des caractéristiques sociales/psychologiques que la cible de notre produit devrait avoir. C’est un outil extrêmement utilisé dans le marketing pour apprendre à cibler correctement les personnes qui souhaiteront acheter ou utiliser notre produit/service."}, 
        {term:"Pré-Processeur", definition:"Un pré-processeur est un programme qui va procèder à des transformations sur du code source avant l’étape de compilation ou d’interprétation. C’est le cas de Sass/Less qui permettent d’écrire du CSS dynamique non interprétable en l’état."},
        {term:"Pull", definition:"Dans le versionning, pull est l’action de récupérer tous les commits qui sont disponibles sur le serveur, et qui, souvent ont été push par vos collègues."}, 
        {term:"Push", definition:"Dans le versionning, push est l’action d’envoyer sur le serveur tous les commits qui ont été faits et qui sont en attente sur votre machine."},
        {term:"Platform As A Service (PaaS)", definition:"Platform as a Service, est un modèle de cloud computing. Le but est de mettre à disposition des outils hardware et logiciels en tant que service. C’est par exemple ce que fait Heroku ou AWS."},
        {term:"Scalable", definition:"Le mot scalable signifie « pouvoir mettre à l’échelle ». On utilise souvent ce mot dans les infrastructures ou les applications. Dans ce cas là, le but est de pouvoir rendre l’application adaptable qu’il y ai une personne ou un million de personnes connectés. L’infrastructure saura donc se rendre « élasitque », « extensible », « adaptable »."}, 
        {term:"Serveur mutualisé", definition:"Se dit d’un hébergement. La mutualisation, contrairement à un VPS, ne permet pas l’accès complet au serveur mais uniquement à un pool de ressources qui pourra varier selon l’affluence des autres sites sur le même hébergement que le votre. C’est donc un type d’hébergement intéressant mais très limité."},
        {term:"SGBD", definition:"SGBD, ou Système de Gestion de Base de Données, est un terme qui désigne un logiciel capable de stocker, manipuler, gérer ou encore partager des données dans une BDD (Base De Données) Quelques exemples: MySQL, Oracle Database, SQLServer."}, 
        {term:"SQL", definition:" Structured Query Language, est un langage permettant la communication avec les systèmes de BDD structurées. Il permet l’insertion, la récupération, la modification ou encore la suppression des informations se trouvant dans la BDD."},
        {term:"Software As A Service (SaaS)", definition:"modèle de cloud computing. Le but est de mettre à disposition un logiciel sur un serveur distant plutôt que sur la machine de l’utilisateur. Exemple avec Shopify ou Netflix."},
        {term:"Transpiler", definition:"Se dit d’un langage qui va être traduit d’un langage vers un autre. TypeScript permet d’écrire du JS « plus propre » mais qui n’est pas compris par les navigateurs. On le transpile en JS afin d’être compréhensible par les navigateurs."}, 
        {term:"UI Design", definition:"L’UI, User Interface, ou interface utilisateur est le rendu visuel final qu’une maquette devra avoir. L’UI se charge donc de tout ce qui est visuel: typos, couleurs, images, etc. C’est la partie esthétique d’une maquette."},
        {term:"UX Design", definition:"L’UX, User Experience, ou expérience utilisateur est l’ergonomie finale qu’une maquette devra avoir. L’UX se charge donc de créer une maquette qui sera la plus intuitive, facile et ergonomique possible ! C’est finalement la tâche la plus invisible mais pourtant la plus importante."}, 
        {term:"Versionning", definition:"Le versionning, ou contrôle des versions, permet dans le développement de travailler sur le code source tout en gardant les versions précédentes. Il apporte aussi la facilité de travailler en équipe de manière fluide et suivie."},
        {term:"Machine Virtuelle (VM)", definition:"Une VM, « Virtual Machine », signifie machine virtuelle en français. C’est l’émulation d’un matériel ou d’un OS de manière totalement autonome et dans un environnement totalement clos."},
        {term:"Serveur Privé Virtuel (VPS)", definition:"Virtual Private Serveur, ou serveur dédié virtuel est une méthode visant à diviser un serveur en plusieurs petits serveurs possédant chacun des caractéristiques fixes. Le processus utiliser permettant de diviser le serveur est la virtualisation dans la plus part des cas."}, 
        {term:"Wireframe", definition:"Le wireframe, ou maquette fonctionnelle, consiste à développer un schéma permettant de définir les zones et composants qu’une interface devra contenir. On pourra, à partir, de ce wireframe créer l’UI."},
        {term:"Workflow", definition:"Workflow, ou flux de travail, représente une suite de tâches ou d’opérations effectuées par une personne, un groupe ou encore un organisme pour finaliser une tâche."}, 
        {term:"", definition:""},

    ];

    // Trier les termes par ordre alphabétique
    glossary.sort((a, b) => a.term.localeCompare(b.term));
    
    // Fonction de recherche
    function searchGlossary(term) {
        const filteredEntries = glossary.filter(entry =>
            entry.term.toLowerCase().includes(term.toLowerCase())
        );
        displayResults(filteredEntries);
    }

    // Affichage des résultats de recherche
    function displayResults(results) {
        lexicon.innerHTML = "";
        results.forEach(entry => {
            const div = document.createElement("div");
            div.classList.add("lexicon-entry");
            div.innerHTML = `<div class="lexicon-term">${entry.term}</div>
                             <div class="lexicon-definition">${entry.definition}</div>`;
            lexicon.appendChild(div);
        });
    }

       // Création de la barre de menu alphabetique
       const alphabet = "abcdefghijklmnopqrstuvwxyz".split("");
       alphabet.forEach(letter => {
           const button = document.createElement("button");
           button.textContent = letter.toUpperCase();
           button.addEventListener("click", function() {
               const filteredEntries = glossary.filter(entry =>
                   entry.term.toLowerCase().startsWith(letter)
               );
               displayResults(filteredEntries);
           });
           alphabetMenu.appendChild(button);
       });

    // Événement de saisie dans la barre de recherche
    searchInput.addEventListener("input", function() {
        const searchTerm = this.value.trim();
        searchGlossary(searchTerm);
    });

    // Afficher tous les termes par défaut
    displayResults(glossary);
});
